### ISSUE TITLE
Quali interfacce utente utilizzare per gli UC Gestione periodo di attività e Gestione offerte?

### ISSUE THREAD

**Issue by MatteoPalombo99** [nicoloabatecola/oobber#11]
Dalla documentazione da lei fornitaci non sono presenti le interfacce utente dei suddetti casi d'uso.
Come ci muoviamo?

**Comment by luca-lezzerini** [comment]
Ho aggiornato UML con nuovi casi d'uso e UI. A breve chiudo il ticket ma ci sto ancora lavorando. Potete fare pull intanto e vedere le novità

**Comment by luca-lezzerini** [comment]
Aggiunta gestione periodi attività
74697a5efb6f5cdddcedc51a2772bfe43a2b3531

**Comment by MatteoPalombo99** [comment]
Lo UC gestione periodo di attività è stato portato a termine, attendiamo l'aggiunta dell'interfaccia dello UC Gestione Offerta

**Comment by luca-lezzerini** [comment]
4696257b6bd6af8375b652208b99e4306a3eddbd
