### ISSUE TITLE
UC login

### ISSUE THREAD

**Issue by capponiFelice92** [nicoloabatecola/oobber#16]

**Comment by capponiFelice92** [comment]
Il login è generico: il server quando riceve la richiesta di login esamina l'utente, se è un viaggiatore rimanda alla home viaggiatore, se è un guidatore manda alla home guidatore

**Comment by nicoloabatecola** [comment]
bf4c52c6b4c0cf7f84f750457499077b9064fe41

**Comment by matteo2025** [comment]
implementata parte server caf1f7aba537d272c007ef28ed2f20b655a029c5
