### ISSUE TITLE
Proprietà email, nel caso d'uso Gestione Utenti sistema

### ISSUE THREAD

**Issue by FedericoRez** [nicoloabatecola/oobber#17]
Nei concetti delle classi l'entità Utente non ha la proprieta "email".
Ma nel caso d'uso registrazione c'è il campo di input "email" ...
Lasciamo la proprieta email per l'entità utente?

![image](https://user-images.githubusercontent.com/78588276/115403862-15ccda80-a1ed-11eb-8a09-3233a64f6f15.png)
![image](https://user-images.githubusercontent.com/78588276/115403896-1cf3e880-a1ed-11eb-8a29-d653cc12271e.png)

**Comment by luca-lezzerini** [comment]
Aggiunta proprietà email su utente. 
5962be8bf0857096131a83c6379ee704c3d2db91
