### ISSUE TITLE
Associazione entità tra RichiestaTragitto e Viaggiatore-Tragitto

### ISSUE THREAD

**Issue by ManuelBava** [nicoloabatecola/oobber#18]
L'associazione dell'entità RichiestaTragitto con Viaggiatore-Tragitto l'abbiamo considerata OneToOne: 
RichiestaTragitto -> Viaggiatore OneToOne 
RichiestaTragitto -> Tragitto OneToOne.

![image](https://user-images.githubusercontent.com/78487457/115411320-a9a1a500-a1f3-11eb-9439-7a2f5e749900.png)

Che ne pensa è giusto come ragionamento?

**Comment by luca-lezzerini** [comment]
Sbagliato.
Viaggiatore - Richiesta -> 1 - 0..*
Richiesta - Tragitto -> 1 - 1
